data = [
    {"name": "Camila Cabello", "description": "Singer-songwriter", "country": "Cuba", "follower_count": 60000000},
    {"name": "Emma Watson", "description": "Actress and activist", "country": "United Kingdom", "follower_count": 50000000},
    {"name": "National Geographic", "description": "Magazine", "country": "United States", "follower_count": 150000000},
    {"name": "Kim Kardashian", "description": "TV personality and businesswoman", "country": "United States", "follower_count": 250000000},
    {"name": "Kylie Jenner", "description": "TV personality and businesswoman", "country": "United States", "follower_count": 240000000},
    {"name": "Cristiano Ronaldo", "description": "Footballer", "country": "Portugal", "follower_count": 400000000},
    {"name": "Dwayne Johnson", "description": "Actor and professional wrestler", "country": "United States", "follower_count": 250000000},
    {"name": "Lionel Messi", "description": "Footballer", "country": "Argentina", "follower_count": 200000000},
    {"name": "Neymar Jr", "description": "Footballer", "country": "Brazil", "follower_count": 170000000},
    {"name": "Taylor Swift", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000},
    {"name": "Kendall Jenner", "description": "TV personality and model", "country": "United States", "follower_count": 150000000},
    {"name": "Virat Kohli", "description": "Cricketer", "country": "India", "follower_count": 120000000},
    {"name": "Jennifer Lopez", "description": "Singer and actress", "country": "United States", "follower_count": 140000000},
    {"name": "Nicki Minaj", "description": "Rapper", "country": "Trinidad and Tobago", "follower_count": 100000000},
    {"name": "Priyanka Chopra", "description": "Actress and singer", "country": "India", "follower_count": 65000000},
    {"name": "NASA", "description": "Space agency", "country": "United States", "follower_count": 70000000},
    {"name": "Ellen DeGeneres", "description": "TV personality and comedian", "country": "United States", "follower_count": 90000000},
    {"name": "Shakira", "description": "Singer-songwriter", "country": "Colombia", "follower_count": 120000000},
    {"name": "Billie Eilish", "description": "Singer-songwriter", "country": "United States", "follower_count": 50000000},
    {"name": "Barack Obama", "description": "Former President of the United States", "country": "United States", "follower_count": 130000000},
    {"name": "Ariana Grande", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000},
    {"name": "Justin Bieber", "description": "Singer-songwriter", "country": "Canada", "follower_count": 200000000},
    {"name": "Selena Gomez", "description": "Singer and actress", "country": "United States", "follower_count": 300000000},
    {"name": "Beyoncé", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000},
    {"name": "Lionel Messi", "description": "Footballer", "country": "Argentina", "follower_count": 200000000},
    {"name": "Neymar Jr", "description": "Footballer", "country": "Brazil", "follower_count": 170000000},
    {"name": "Taylor Swift", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000},
    {"name": "Kendall Jenner", "description": "TV personality and model", "country": "United States", "follower_count": 150000000},
    {"name": "Virat Kohli", "description": "Cricketer", "country": "India", "follower_count": 120000000},
    {"name": "Jennifer Lopez", "description": "Singer and actress", "country": "United States", "follower_count": 140000000},
    {"name": "Nicki Minaj", "description": "Rapper", "country": "Trinidad and Tobago", "follower_count": 100000000},
    {"name": "Priyanka Chopra", "description": "Actress and singer", "country": "India", "follower_count": 65000000},
    {"name": "NASA", "description": "Space agency", "country": "United States", "follower_count": 70000000},
    {"name": "Ellen DeGeneres", "description": "TV personality and comedian", "country": "United States", "follower_count": 90000000},
    {"name": "Shakira", "description": "Singer-songwriter", "country": "Colombia", "follower_count": 120000000},
    {"name": "Billie Eilish", "description": "Singer-songwriter", "country": "United States", "follower_count": 50000000},
    {"name": "Barack Obama", "description": "Former President of the United States", "country": "United States", "follower_count": 130000000},
    {"name": "Ariana Grande", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000},
    {"name": "Justin Bieber", "description": "Singer-songwriter", "country": "Canada", "follower_count": 200000000},
    {"name": "Selena Gomez", "description": "Singer and actress", "country": "United States", "follower_count": 300000000},
    {"name": "Beyoncé", "description": "Singer-songwriter", "country": "United States", "follower_count": 180000000}
]
